import type { Metadata } from "next";
import { Heebo } from "next/font/google";
import "../styles/base/index.css";
import StoreProvider from "./StoreProvider";

const heebo = Heebo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BuildStore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={heebo.className}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
